#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'pre commit checklist intiated'

#Checking for styling errors
npm run formatCheck || 
(
    echo 'styling failed this shouldnt happen
            please fix the styling errors above.'
    false;
)

#Checking for syntax errors
npm run lint ||
(
    echo 'syntax check failed, did we forget an await?
            please fix the following syntax errors above'
    false;
)

#If everything passes we can commit
echo 'Congrats! the your code has passed the pre-commit checklist'
